Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: chatgpt-next-web
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: 一键部署您的跨平台ChatGPT应用，支持完整的Markdown、LaTex公式、Mermaid流程图等。界面美观，响应迅速，兼容深色模式和PWA，快速加载，数据隐私安全。功能丰富，方便创建、分享个性化对话，内含海量中英文prompt，自动压缩聊天记录，支持多国语言。
    Image: 'resources/icons/chatgpt-next-web.jpg'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: chatgpt-next-web
    Description: chatgpt-next-web
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: centos_7_9_x64_20G_alibase_20240403.vhd
    SystemDiskSize: 40
    InstanceType: ecs.c7.2xlarge
    InternetMaxBandwidthOut: 100
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
      #!/bin/bash
      sudo yum update -y
      sudo mkdir -p /etc/docker
      sudo tee /etc/docker/daemon.json <<-'EOF'
      {
          "registry-mirrors": [
              "https://0vmzj3q6.mirror.aliyuncs.com",
              "https://docker.m.daocloud.io",
              "https://mirror.baidubce.com",
              "https://dockerproxy.com",
              "https://mirror.iscas.ac.cn",
              "https://huecker.io",
              "https://dockerhub.timeweb.cloud",
              "https://noohub.ru",
              "https://vlgh0kqj.mirror.aliyuncs.com"
          ]
      }
      EOF
      sudo systemctl daemon-reload
      
      yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
      yum makecache fast
      yum install -y git docker-ce jq
      systemctl enable docker
      systemctl start docker
      
      docker pull yidadaa/chatgpt-next-web
